services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1337
      - POSTGRES_DB=Rain
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"


volumes:
  pgdata:
      driver: local