[app_settings]
app_port = 8000
app_version = "1.0.0"
app_name = "Rain"
app_host = "127.0.0.1"
app_mount = "/api/v1"

[db_settings]
db_name = "Rain"
db_user = "postgres"
db_password = "1337"
db_host = "127.0.0.1"
db_port = "5432"
db_key = "jhuerhg84gy948gh49jg5h4puhg"
db_algorythm = "HS256"